apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
   type: restapi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: flask-app
  replicas: 4
  template:
    metadata:
      name: flask-app-tmpl
      labels:
        app: flask-app
    spec:
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: flask-app-pvc
      containers:
      - name: flsak-app
        image: flask_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: test-vol
          mountPath: /flask_sr/base
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
              path: /api/somedata/0
              port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/somedata/0
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
   - protocol: "TCP"
     port: 80
     targetPort: 5000
