name: Docker Image CI

env:
  DOCKERTAG: "europe-central2-docker.pkg.dev/celtic-beacon-387519/amossg-docker/testdocker"
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.DOCKER_PUSH }}'
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: europe-central2-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.DOCKER_PUSH }}
    - name: docker build
      run: docker build -t ${{ env.DOCKERTAG}} .
    - name: docker push
      run: docker push ${{ env.DOCKERTAG}}
      
