name: My GitHub Action
on:
  workflow_dispatch

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run
      run: cat txt.txt
